[build]
  publish = "dist"
  command = "rm -rf package-lock.json node_modules && npm install --legacy-peer-deps && npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NPM_CONFIG_OPTIONAL = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 